### ISSUE TITLE
Display Feature Properties in Side Panel

### ISSUE THREAD

**Issue by dellisd** [cuhacking/atlas-editor#3]
When a user clicks on a feature on the map, its properties should be shown in the editor's side panel.

Subtasks:

- [x] #7
- [x] #8

(the display doesn't need to be fancy. Just a few rows of text for this task)

**Comment by deenhaque** [comment]
This is an example of a JSON object who's `properties` would be shown on the side panel.
```
{
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [0, 0]
  },
  "properties": {
    "foo": "value",
    "bar": 12
  }
}
```
